collections:
  - name: community.network
    version: 3.1.0

  - name: fortinet.fortios
    version: 2.7.0

  - name: junipernetworks.junos
    version: 2.1.0

  - name: cisco.ios
    version: 2.0.0

  - name: mikrotik.routeros
    version: 2.1.0

dependencies:
  - name: ansible.pylibssh
    src: https://github.com/ansible/ansible-pylibssh.git
    version: master
