---
- name: Get Configuration
  hosts: Cisco_Routers, MikroTik_Router, Juniper_Router, Fortinet_Router
  gather_facts: false
  vars: 
    output_directory: "/home/atoman/Plocha/config"

  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks: Tasks/getConfigTask.yaml

    - name: Save Cisco IOS configuration to file
      ansible.builtin.copy:
        content: "{{ ios_output.stdout[0] if ios_output.stdout is defined else '' }}"
        dest: "{{ output_directory }}/{{ inventory_hostname }}-ios-config.txt"
        mode: '0644'
        backup: yes
      when: ansible_network_os == 'ios'

    - name: Save MikroTik configuration to file
      ansible.builtin.copy:
        content: "{{ mikrotik_output.stdout[0] if mikrotik_output.stdout is defined else '' }}"
        dest: "{{ output_directory }}/{{ inventory_hostname }}-mikrotik-config.txt"
        mode: '0644'
        backup: yes
      when: ansible_network_os == 'routeros'

    - name: Save Juniper configuration to file
      ansible.builtin.copy:
        content: "{{ juniper_output.stdout[0] if juniper_output.stdout is defined else '' }}"
        dest: "{{ output_directory }}/{{ inventory_hostname }}-juniper-config.txt"
        mode: '0644'
        backup: yes
      when: ansible_network_os == 'junos'

    - name: Save Fortinet configuration to file
      ansible.builtin.copy:
        content: "{{ fortinet_output | to_nice_yaml }}"
        dest: "{{ output_directory }}/{{ inventory_hostname }}-fortinet-config.txt"
        mode: '0644'
      when: ansible_network_os == 'fortinet.fortios.fortios'
