---
- name: Configure SNMP, CDP, and LLDP across multiple platforms
  hosts: Cisco_Router, MikroTik_Router, Juniper_Router
  gather_facts: false
  vars_files:
    - vars_SNMP.yaml

  tasks:
    - name: Configure Cisco devices
      when: ansible_network_os == 'ios'
      block:
        - name: Enable LLDP service
          cisco.ios.ios_lldp:
            state: enabled

        - name: Configure SNMP server
          cisco.ios.ios_snmp_server:
            config:
              communities:
                - name: "{{ snmp_community }}"
                  ro: true
              contact: "Pavel.Segec@fri.uniza.sk"
              location: "{{ snmp_location }}"

        - name: Enable CDP
          cisco.ios.ios_command:
            commands:
              - "configure terminal"
              - "cdp run"

    - name: Configure MikroTik devices
      when: ansible_network_os == 'routeros'
      block:
        - name: Enable LLDP, MNDP, and CDP
          community.routeros.command:
            commands:
              - /ip neighbor discovery-settings set discover-interface-list=all protocol=lldp,mndp,cdp

        - name: Configure SNMP
          community.routeros.command:
            commands:
              - /snmp set contact=\"Pavel.Segec@fri.uniza.sk\" enabled=yes location={{ snmp_location }} trap-community={{ snmp_community }} trap-version=2

    - name: Configure Juniper devices
      when: ansible_network_os == 'junos'
      block:
        - name: Set a variable specifically for Junos devices
          ansible.builtin.set_fact:
            ansible_connection: ansible.netcommon.netconf

        - name: Enable LLDP globally
          junipernetworks.junos.junos_lldp_global:
            config:
              enabled: "true"
#            state: present

        - name: Configure SNMP server
          junipernetworks.junos.junos_snmp_server:
            config:
              communities:
                - name: "{{ snmp_community }}"
                  authorization: read-only
              contact: "Pavel.Segec@fri.uniza.sk"
              location: "{{ snmp_location }}"
#              state: replaced

    - name: Configure Fortinet devices
      when: ansible_network_os == 'fortios'
      block:
        - name: Configure SNMP community
          fortinet.fortios.fortios_switch_controller_snmp_community:
            state: present
            switch_controller_snmp_community:
              id: 1
              name: "{{ snmp_community }}"
              status: enable

        - name: Configure SNMP system information
          fortinet.fortios.fortios_switch_controller_snmp_sysinfo:
            member_state: present
            switch_controller_snmp_sysinfo:
              location: "{{ snmp_location }}"
              contact_info: "Pavel.Segec@fri.uniza.sk"

        - name: Enable LLDP globally
          fortinet.fortios.fortios_switch_controller_lldp_settings:
            switch_controller_lldp_settings:
              status: enable
